{% set name = "autopxd2" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: c0c1440f4d99a125ca406b2e08a62ee8558c2e6cc7d58f3849eec63f6a0ade37

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - pycparser
    - python >={{ python_min }}

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
