{% set name = "autopxd2" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autopxd2-{{ version }}.tar.gz
  sha256: bb1556cf62d25d6a4362f405af196b9b10355d06a0c874df15fe2185a1ca3aa7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - autopxd = autopxd:cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - pycparser
    - python >=3.7

test:
  imports:
    - autopxd
  commands:
    - pip check
    - autopxd --help
  requires:
    - pip

about:
  home: https://github.com/gabrieldemarmiesse/python-autopxd2
  summary: Automatically generate Cython pxd files from C headers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
